<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProgramsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('programs')->insert([
            [
            'abbreviation' => 'MT',
            'program_id' => 1,
            'program_code' => 'BSMT',
            'program_name' => 'BS Medical Technology',
            'program_description' => 'Focuses on laboratory sciences, training students in clinical procedures and diagnostics used to detect, diagnose, and treat diseases.',
            'department_id' => 5,
            ],
            [
            'abbreviation' => 'PH',
            'program_id' => 2,
            'program_code' => 'BS-PHAR',
            'program_name' => 'BS Pharmacy',
            'program_description' => 'Prepares students for careers in the pharmaceutical industry, emphasizing drug therapy, patient care, and medication management.',
            'department_id' => 5,
            ],
            [
            'abbreviation' => 'RT',
            'program_id' => 3,
            'program_code' => 'BS-RADTECH',
            'program_name' => 'BS Radiologic Technology',
            'program_description' => 'Trains students in medical imaging techniques, including X-ray, MRI, and CT scans, to assist in patient diagnosis.',
            'department_id' => 5,
            ],
            [
            'abbreviation' => 'BIO',
            'program_id' => 4,
            'program_code' => 'BS-BIO',
            'program_name' => 'BS Biology',
            'program_description' => 'Provides a broad understanding of biological sciences, covering genetics, ecology, and microbiology as foundations for careers in research, healthcare, and biotechnology.',
            'department_id' => 5,
            ],
            [
            'abbreviation' => 'BACOMM',
            'program_id' => 5,
            'program_code' => 'B-COM',
            'program_name' => 'Bachelor of Arts in Communication',
            'program_description' => 'Focuses on communication theory, media studies, and public relations, preparing students for careers in journalism, media, and corporate communication.',
            'department_id' => 6,
            ],
            [
            'abbreviation' => 'ABFS',
            'program_id' => 6,
            'program_code' => 'AB-FS',
            'program_name' => 'AB Foreign Service',
            'program_description' => 'Prepares students for diplomatic careers with training in international relations, global politics, and cultural studies.',
            'department_id' => 6,
            ],
            [
            'abbreviation' => 'ABLS',
            'program_id' => 7,
            'program_code' => 'AB-LS',
            'program_name' => 'AB Legal Studies',
            'program_description' => 'Offers foundational legal knowledge and critical thinking skills, ideal for students aiming for law school or legal assistant roles.',
            'department_id' => 6,
            ],
            [
            'abbreviation' => 'ECED',
            'program_id' => 8,
            'program_code' => 'BECE',
            'program_name' => 'Bachelor of Early Childhood Education',
            'program_description' => 'Equips students with teaching methods and psychology for educating young children, particularly in preschool and elementary levels.',
            'department_id' => 6,
            ],
            [
            'abbreviation' => 'SED',
            'program_id' => 9,
            'program_code' => 'BSE',
            'program_name' => 'Bachelor in Secondary Education',
            'program_description' => 'Prepares future educators to teach at the secondary level, specializing in pedagogy and adolescent development.',
            'department_id' => 6,
            ],
            [
            'abbreviation' => 'PSYCH',
            'program_id' => 10,
            'program_code' => 'BS-PSYCH',
            'program_name' => 'BS Psychology',
            'program_description' => 'Covers psychological theories and practices, preparing students for roles in counseling, human resources, or further studies in psychology.',
            'department_id' => 6,
            ],
            [
            'abbreviation' => 'ACC',
            'program_id' => 11,
            'program_code' => 'BSA',
            'program_name' => 'BS Accountancy',
            'program_description' => 'Provides expertise in financial accounting, taxation, and auditing, essential for roles as accountants or financial analysts.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'HRM',
            'program_id' => 12,
            'program_code' => 'BA-HRM',
            'program_name' => 'BS Business Administration major in Human Resource Development Management',
            'program_description' => 'Trains students in managing employee relations, talent acquisition, and organizational behavior.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'MA',
            'program_id' => 13,
            'program_code' => 'BA-MA',
            'program_name' => 'BS Business Administration major in Management Accounting',
            'program_description' => 'Equips students with skills in budgeting, cost management, and financial planning within organizations.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'MM',
            'program_id' => 14,
            'program_code' => 'BA-MM',
            'program_name' => 'BS Business Administration major in Marketing Management',
            'program_description' => 'Focuses on marketing strategies, consumer behavior, and brand management, preparing students for marketing careers.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'OM',
            'program_id' => 15,
            'program_code' => 'BA-OM',
            'program_name' => 'BS Business Administration major in Operations Management',
            'program_description' => 'Teaches principles of production, logistics, and supply chain management to streamline business processes.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'CA',
            'program_id' => 16,
            'program_code' => 'BSCA',
            'program_name' => 'BS Customs Administration',
            'program_description' => 'Prepares students for careers in customs, trade compliance, and logistics within global supply chains.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'ENTREP',
            'program_id' => 17,
            'program_code' => 'BS-ENTR-AI',
            'program_name' => 'BS Entrepreneurship with specialization in Aesthetics Industry Management',
            'program_description' => 'Focuses on business startup processes and managing ventures specifically within the aesthetics and wellness industry.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'REM',
            'program_id' => 18,
            'program_code' => 'BSREM',
            'program_name' => 'BS Real Estate Management',
            'program_description' => 'Provides knowledge in real estate laws, property management, and market analysis, preparing students for roles in real estate.',
            'department_id' => 7,
            ],
            [
            'abbreviation' => 'ARCH',
            'program_id' => 19,
            'program_code' => 'BS-ARCH',
            'program_name' => 'Bachelor of Science in Architecture',
            'program_description' => 'Teaches design principles, architectural theory, and construction techniques for careers in architecture.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'CS',
            'program_id' => 20,
            'program_code' => 'BSCS',
            'program_name' => 'BS Computer Science',
            'program_description' => 'Computer Science will be able to learn about other subjects such as machine learning, blockchain, social hacking, and data analytics.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'IT',
            'program_id' => 21,
            'program_code' => 'BSIT',
            'program_name' => 'BS Information Technology',
            'program_description' => 'Equips students with the basic ability to conceptualize, design, and implement software applications.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'LIS',
            'program_id' => 22,
            'program_code' => 'LIS',
            'program_name' => 'Bachelor of Library and Information Science',
            'program_description' => 'Trains students in library management, information retrieval, and cataloging, preparing them for roles in library sciences.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'ENG',
            'program_id' => 23,
            'program_code' => 'BSAE',
            'program_name' => 'Bachelor of Science in Aeronautical Engineering',
            'program_description' => 'Prepares students for the aviation industry with training in aircraft design, systems, and safety.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'CE',
            'program_id' => 24,
            'program_code' => 'BSCE',
            'program_name' => 'BS Civil Engineering',
            'program_description' => 'Designed to prepare graduates to apply knowledge of mathematics, calculus-based physics, chemistry, and at least one additional area of basic science.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'CPE',
            'program_id' => 25,
            'program_code' => 'BSCPE',
            'program_name' => 'BS Computer Engineering',
            'program_description' => 'Focuses on the development and optimization of both computer hardware and software.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'ET',
            'program_id' => 26,
            'program_code' => 'BET-CTM',
            'program_name' => 'Bachelor of Engineering Technology',
            'program_description' => 'Teaches construction practices and project management in engineering settings.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'EE',
            'program_id' => 27,
            'program_code' => 'BSECE',
            'program_name' => 'BS in Electronics Engineering',
            'program_description' => 'Focuses on electronic devices, telecommunications, and signal processing.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'IE',
            'program_id' => 28,
            'program_code' => 'BSIE',
            'program_name' => 'Bachelor of Science in Industrial Engineering',
            'program_description' => 'Teaches process optimization, production planning, and quality control in various industries.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'ME',
            'program_id' => 29,
            'program_code' => 'BSME',
            'program_name' => 'BS Mechanical Engineering',
            'program_description' => 'Covers thermodynamics, mechanical design, and manufacturing processes for engineering roles.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'FA',
            'program_id' => 30,
            'program_code' => 'BFA',
            'program_name' => 'Bachelor of Fine Arts',
            'program_description' => 'Offers creative training in painting, sculpture, and visual arts for careers in the arts sector.',
            'department_id' => 2,
            ],
            [
            'abbreviation' => 'MMA',
            'program_id' => 31,
            'program_code' => 'BMMA',
            'program_name' => 'Bachelor of Multimedia Arts',
            'program_description' => 'Combines digital media, graphic design, and animation, preparing students for multimedia industries.',
            'department_id' => 2,
            ],
            [
            'abbreviation' => 'PHOTO',
            'program_id' => 32,
            'program_code' => 'B-PHOTO',
            'program_name' => 'Bachelor in Photography',
            'program_description' => 'Teaches photography techniques and visual storytelling for careers in professional photography.',
            'department_id' => 1,
            ],
            [
            'abbreviation' => 'TM',
            'program_id' => 33,
            'program_code' => 'BS-ITTM',
            'program_name' => 'BS International Travel and Tourism Management',
            'program_description' => 'Prepares students for roles in tourism management, including travel planning and tour operations.',
            'department_id' => 3,
            ],
            [
            'abbreviation' => 'TM',
            'program_id' => 34,
            'program_code' => 'BS-ITTM-HW',
            'program_name' => 'BS International Travel and Tourism Management (Health and Wellness)',
            'program_description' => 'Specializes in health and wellness tourism, focusing on wellness programs and spa management.',
            'department_id' => 3,
            ],
            [
            'abbreviation' => 'HM',
            'program_id' => 35,
            'program_code' => 'BSHM',
            'program_name' => 'BS International Hospitality Management',
            'program_description' => 'Prepares students to become effective leaders, managers, and/or entrepreneurs in the global hospitality industry.',
            'department_id' => 3,
            ],
            [
            'abbreviation' => 'ND',
            'program_id' => 36,
            'program_code' => 'BSND',
            'program_name' => 'BS Nutrition and Dietetics',
            'program_description' => 'Prepares students to become dietitians or nutritionists, focusing on meal planning and health management.',
            'department_id' => 3,
            ],
            [
            'abbreviation' => 'NURS',
            'program_id' => 37,
            'program_code' => 'BSN',
            'program_name' => 'BS Nursing',
            'program_description' => 'Provides clinical and theoretical training in patient care, preparing students to become registered nurses.',
            'department_id' => 4,
            ],
        ]);
    }
}
